version: "3"

services:

  foo:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - caddy
    expose:
      - 3000

networks:
  caddy:
    external: true
